// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.DataAccessLayer;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(MPMSDbContext))]
    [Migration("20260609092013_UpdatedModelsWithSeedData")]
    partial class UpdatedModelsWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Defect", b =>
                {
                    b.Property<int>("DefectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DefectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductionOrderOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("ReporterUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("DefectId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionOrderOrderId");

                    b.HasIndex("ReporterUserId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("backend.Models.DowntimeReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DowntimeReason");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Machine Breakdown"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Power Failure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Material Shortage"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tool Change"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Planned Maintenance"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Unplanned Maintenance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Operator Absence"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Quality Issue"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Setup Changeover"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Network Failure"
                        });
                });

            modelBuilder.Entity("backend.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("FloorNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TerminalNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            FloorNo = "1",
                            LocationName = "Assembly Line",
                            Status = 0,
                            TerminalNo = "A1"
                        },
                        new
                        {
                            LocationId = 2,
                            FloorNo = "1",
                            LocationName = "Packaging Line",
                            Status = 0,
                            TerminalNo = "A2"
                        },
                        new
                        {
                            LocationId = 3,
                            FloorNo = "1",
                            LocationName = "Quality Control",
                            Status = 0,
                            TerminalNo = "A3"
                        });
                });

            modelBuilder.Entity("backend.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MachineId"));

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MachineId");

                    b.HasIndex("LocationId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = 1,
                            LocationId = 1,
                            MachineCode = "ASM-001",
                            MachineName = "Conveyor Belt A",
                            Status = 0
                        },
                        new
                        {
                            MachineId = 2,
                            LocationId = 1,
                            MachineCode = "ASM-002",
                            MachineName = "Robotic Arm A",
                            Status = 0
                        },
                        new
                        {
                            MachineId = 3,
                            LocationId = 2,
                            MachineCode = "PKG-001",
                            MachineName = "Packaging Machine A",
                            Status = 0
                        },
                        new
                        {
                            MachineId = 4,
                            LocationId = 2,
                            MachineCode = "PKG-002",
                            MachineName = "Labeling Machine A",
                            Status = 0
                        },
                        new
                        {
                            MachineId = 5,
                            LocationId = 3,
                            MachineCode = "QC-001",
                            MachineName = "Vision Inspection System",
                            Status = 0
                        });
                });

            modelBuilder.Entity("backend.Models.MachineReading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReadingId"));

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<double>("PowerConsumption")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Vibration")
                        .HasColumnType("double precision");

                    b.HasKey("ReadingId");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineReadings");
                });

            modelBuilder.Entity("backend.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<int>("EngineerId")
                        .HasColumnType("integer");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.HasIndex("EngineerId");

                    b.HasIndex("MachineId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("backend.Models.ProductionAnalytics", b =>
                {
                    b.Property<int>("AnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnalyticsId"));

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DefectRate")
                        .HasColumnType("double precision");

                    b.Property<double>("Downtime")
                        .HasColumnType("double precision");

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.HasKey("AnalyticsId");

                    b.HasIndex("MachineId");

                    b.ToTable("ProductionAnalyticss");
                });

            modelBuilder.Entity("backend.Models.ProductionOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductionPlanPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionPlanPlanId");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("backend.Models.ProductionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("integer");

                    b.HasKey("PlanId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("ProductionPlans");
                });

            modelBuilder.Entity("backend.Models.ProductionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionPlanId");

                    b.ToTable("ProductionRecords");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("HashKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Defect", b =>
                {
                    b.HasOne("backend.Models.Machine", "Machine")
                        .WithMany("Defects")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("Defects")
                        .HasForeignKey("ProductionOrderOrderId");

                    b.HasOne("backend.Models.User", "Reporter")
                        .WithMany("ReportedDefects")
                        .HasForeignKey("ReporterUserId");

                    b.Navigation("Machine");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("backend.Models.Machine", b =>
                {
                    b.HasOne("backend.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("backend.Models.MachineReading", b =>
                {
                    b.HasOne("backend.Models.Machine", "Machine")
                        .WithMany("MachineReadings")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("backend.Models.MaintenanceLog", b =>
                {
                    b.HasOne("backend.Models.User", "Engineer")
                        .WithMany()
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Machine", "Machine")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engineer");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("backend.Models.ProductionAnalytics", b =>
                {
                    b.HasOne("backend.Models.Machine", "Machine")
                        .WithMany("Analytics")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("backend.Models.ProductionOrder", b =>
                {
                    b.HasOne("backend.Models.Machine", "Machine")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ProductionPlan", "ProductionPlan")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("ProductionPlanPlanId");

                    b.Navigation("Machine");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("backend.Models.ProductionPlan", b =>
                {
                    b.HasOne("backend.Models.User", "Creator")
                        .WithMany("ProductionPlans")
                        .HasForeignKey("CreatorUserId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("backend.Models.ProductionRecord", b =>
                {
                    b.HasOne("backend.Models.ProductionPlan", "ProductionPlan")
                        .WithMany()
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("backend.Models.Machine", b =>
                {
                    b.Navigation("Analytics");

                    b.Navigation("Defects");

                    b.Navigation("MachineReadings");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("ProductionOrders");
                });

            modelBuilder.Entity("backend.Models.ProductionOrder", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("backend.Models.ProductionPlan", b =>
                {
                    b.Navigation("ProductionOrders");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("ProductionPlans");

                    b.Navigation("ReportedDefects");
                });
#pragma warning restore 612, 618
        }
    }
}
